"""theygent IR — single source of truth for the cross-plane data contract.

The inference-plane registration payload (``registration.py``) and the capabilities response
are frozen here. The Agent Graph IR (``graph.py`` / ``contenthash.py``) defines
the document envelope, nodes/edges, model bindings, the ``kind`` taxonomy, and the
content-hash rule. This package stays pure — Pydantic models + static graph algorithms, no
engine SDK, no gateway client. Execution (the walker) lives in the control-plane.
"""

from theygent_ir.contenthash import content_hash
from theygent_ir.graph import (
    EXECUTABLE_TYPES,
    NODE_TYPE_KIND,
    BuiltinTool,
    Edge,
    GraphValidationError,
    GuardrailCheck,
    GuardrailConfig,
    GuardrailModel,
    GuardrailRule,
    HttpTool,
    HumanConfig,
    ImagineConfig,
    IRDocument,
    LlmConfig,
    LoopConfig,
    MapConfig,
    McpTool,
    McpToolConfig,
    ModelBinding,
    Node,
    NodeKind,
    Port,
    PortRole,
    Ports,
    QuotaConfig,
    RateLimitConfig,
    RouterConfig,
    SpeakConfig,
    SubgraphConfig,
    ToolConfig,
    TranscribeConfig,
    TransformConfig,
    parse_document,
    topological_order,
    validate_graph,
)
from theygent_ir.registration import (
    BINDING_NAMES,
    MANAGED_BINDINGS,
    MODALITIES,
    Capabilities,
    Lifecycle,
    ManagedBinding,
    Modality,
    ReachableBinding,
    RegistrationPayload,
    parse_registration,
)

__all__ = [
    # registration
    "BINDING_NAMES",
    # agent graph IR
    "EXECUTABLE_TYPES",
    "MANAGED_BINDINGS",
    "MODALITIES",
    "NODE_TYPE_KIND",
    "BuiltinTool",
    "Capabilities",
    "Edge",
    "GraphValidationError",
    "GuardrailCheck",
    "GuardrailConfig",
    "GuardrailModel",
    "GuardrailRule",
    "HttpTool",
    "HumanConfig",
    "IRDocument",
    "ImagineConfig",
    "Lifecycle",
    "LlmConfig",
    "LoopConfig",
    "ManagedBinding",
    "MapConfig",
    "McpTool",
    "McpToolConfig",
    "Modality",
    "ModelBinding",
    "Node",
    "NodeKind",
    "Port",
    "PortRole",
    "Ports",
    "QuotaConfig",
    "RateLimitConfig",
    "ReachableBinding",
    "RegistrationPayload",
    "RouterConfig",
    "SpeakConfig",
    "SubgraphConfig",
    "ToolConfig",
    "TranscribeConfig",
    "TransformConfig",
    "content_hash",
    "parse_document",
    "parse_registration",
    "topological_order",
    "validate_graph",
]
